name: bci-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow=2.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - h5py
  - pillow
  - tqdm
  - jupyterlab
  - pip
  - pip:
    - tensorflow-addons
    - tensorflow-datasets
